export const GET_GROUP_DETAILS_REQ = "GET_GROUP_DETAILS_REQ";
export const GET_GROUP_DETAILS_SUCCESS = "GET_GROUP_DETAILS_SUCCESS";
export const GET_GROUP_DETAILS_ERROR = "GET_GROUP_DETAILS_ERROR";

export const GET_GROUP_FILES_REQ = "GET_GROUP_FILES_REQ";
export const GET_GROUP_FILES_SUCCESS = "GET_GROUP_FILES_SUCCESS";
export const GET_GROUP_FILES_ERROR = "GET_GROUP_FILES_ERROR";

export const PUBLISH_FILE_TO_GROUP_REQ = "PUBLISH_FILE_TO_GROUP_REQ";
export const PUBLISH_FILE_TO_GROUP_SUCCESS = "PUBLISH_FILE_TO_GROUP_SUCCESS";
export const PUBLISH_FILE_TO_GROUP_ERROR = "PUBLISH_FILE_TO_GROUP_ERROR";

export const DELETE_FILE_FROM_GROUP_REQ = "DELETE_FILE_FROM_GROUP_REQ";
export const DELETE_FILE_FROM_GROUP_SUCCESS = "DELETE_FILE_FROM_GROUP_SUCCESS";
export const DELETE_FILE_FROM_GROUP_ERROR = "DELETE_FILE_FROM_GROUP_ERROR";

export const DOWNLOAD_FILE_FROM_GROUP_REQ = "DOWNLOAD_FILE_FROM_GROUP_REQ";
export const DOWNLOAD_FILE_FROM_GROUP_SUCCESS =
  "DOWNLOAD_FILE_FROM_GROUP_SUCCESS";
export const DOWNLOAD_FILE_FROM_GROUP_ERROR = "DOWNLOAD_FILE_FROM_GROUP_ERROR";
