export const SHOW_GROUPS_REQ = "SHOW_GROUPS_REQ";
export const SHOW_GROUPS_SUCCESS = "SHOW_GROUPS_SUCCESS";
export const SHOW_GROUPS_ERROR = "SHOW_GROUPS_ERROR";
export const SHOW_AVAILABLE_GROUPS_REQ = "SHOW_AVAILABLE_GROUPS_REQ";
export const SHOW_AVAILABLE_GROUPS_SUCCESS = "SHOW_AVAILABLE_GROUPS_SUCCESS";
export const SHOW_AVAILABLE_GROUPS_ERROR = "SHOW_AVAILABLE_GROUPS_ERROR";
export const CREATE_GROUP_REQ = "CREATE_GROUP_REQ";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_ERROR = "CREATE_GROUP_ERROR";
export const CHANGE_GROUP_CREATION_VALUE = "CHANGE_GROUP_CREATION_VALUE";
export const CLEAR_GROUP_CREATION_VALUES = "CLEAR_GROUP_CREATION_VALUES";
export const SET_GROUP_LIST_PAGE = "SET_GROUP_LIST_PAGE";
export const JOIN_GROUP_REQ = "JOIN_GROUP_REQ";
export const JOIN_GROUP_SUCCESS = "JOIN_GROUP_SUCCESS";
export const JOIN_GROUP_ERROR = "JOIN_GROUP_ERROR";
export const SET_AVAILABLE_GROUPS_DIALOG_PAGE =
  "SET_AVAILABLE_GROUPS_DIALOG_PAGE";
export const DELETE_GROUP_REQ = "DELETE_GROUP_REQ";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";
export const DELETE_GROUP_ERROR = "DELETE_GROUP_ERROR";
export const LEAVE_GROUP_REQ = "LEAVE_GROUP_REQ";
export const LEAVE_GROUP_SUCCESS = "LEAVE_GROUP_SUCCESS";
export const LEAVE_GROUP_ERROR = "LEAVE_GROUP_ERROR";
export const SEARCH_USER_REQ = "SEARCH_USER_REQ";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_ERROR = "SEARCH_USER_ERROR";
export const SET_AVAILABLE_USERS_DIALOG_PAGE =
  "SET_AVAILABLE_USERS_DIALOG_PAGE";
export const RESET_AVAILABLE_USERS = "RESET_AVAILABLE_USERS";
export const INVITE_USER_REQ = "INVITE_USER_REQ";
export const INVITE_USER_SUCCESS = "INVITE_USER_SUCCESS";
export const INVITE_USER_ERROR = "INVITE_USER_ERROR";

export const INPUT_KEYS_CREATE_GROUP = {
  GROUP_NAME: "GROUP_NAME",
  IS_GROUP_PUBLIC: "IS_GROUP_PUBLIC",
  GROUP_DESCRIPTION: "GROUP_DESCRIPTION",
  FILE_COUNT_LIMIT: "FILE_COUNT_LIMIT",
  FILE_SIZE_LIMIT: "FILE_SIZE_LIMIT",
};
