export const FILE_UPLOAD_REQ = "FILE_UPLOAD_REQ";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR";
export const SET_INVENTORY_LIST_PAGE = "SET_INVENTORY_LIST_PAGE";
export const RESET_INVENTORY_LIST_PAGE = "RESET_INVENTORY_LIST_PAGE";
export const GET_FILES_REQ = "GET_FILES_REQ";
export const GET_FILES_SUCCESS = "GET_FILES_SUCCESS";
export const GET_FILES_ERROR = "GET_FILES_ERROR";

export const DELETE_FILE_FROM_INVENTORY_REQ = "DELETE_FILE_FROM_INVENTORY_REQ";
export const DELETE_FILE_FROM_INVENTORY_SUCCESS =
  "DELETE_FILE_FROM_INVENTORY_SUCCESS";
export const DELETE_FILE_FROM_INVENTORY_ERROR =
  "DELETE_FILE_FROM_INVENTORY_ERROR";

export const DOWNLOAD_FILE_FROM_INVENTORY_REQ =
  "DOWNLOAD_FILE_FROM_INVENTORY_REQ";
export const DOWNLOAD_FILE_FROM_INVENTORY_SUCCESS =
  "DOWNLOAD_FILE_FROM_INVENTORY_SUCCESS";
export const DOWNLOAD_FILE_FROM_INVENTORY_ERROR =
  "DOWNLOAD_FILE_FROM_INVENTORY_ERROR";
