export const NOTIFICATIONS_REQ = "NOTIFICATIONS_REQ";
export const NOTIFICATIONS_SUCCESS = "NOTIFICATIONS_SUCCESS";
export const NOTIFICATIONS_ERROR = "NOTIFICATIONS_ERROR";

export const UPDATE_NOTIFICATION_REQ = "UPDATE_NOTIFICATION_REQ";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_ERROR = "UPDATE_NOTIFICATION_ERROR";

export const DECLINE_NOTIFICATION_REQ = "DECLINE_NOTIFICATION_REQ";
export const DECLINE_NOTIFICATION_SUCCESS = "DECLINE_NOTIFICATION_SUCCESS";
export const DECLINE_NOTIFICATION_ERROR = "DECLINE_NOTIFICATION_ERROR";
