export const PAGINATION = {
  GROUPS_PER_PAGE: 8,
  FILES_PER_PAGE: 8,
  USERS_PER_PAGE: 8,
};

export const NOTIFICATIONS = {
  NOTIFICATION_TYPE_GROUP_INVITE: 1,
  NOTIFICATION_TYPE_GROUP_UPLOAD: 2,
  NOTIFICATIONS_PER_PAGE: 4,
  REFRESH_RATE_IN_MS: 30000,
};

//29 minutes
export const AUTO_LOG_OUT_TIMEOUT_MS = 1740000;

//20 MByte
export const MAX_UPLOAD_SIZE_MBYTE = 20;
export const MAX_UPLOAD_SIZE_BYTE = MAX_UPLOAD_SIZE_MBYTE * 1000 * 1000;

export const INVENTORY_LIST_MAX_STRING_LENGTH = 42;
